### ISSUE TITLE
allow more characters (like {})  in URI fields

### ISSUE THREAD

**Issue by marc-portier** [epos-eu/SHAPEness-Metadata-Editor#3]
We are looking at this tool to use it to produce a JINJA2 Template to produce the actual ttl from an existing database system listing datasets (and dataservices)

So we would like to enter URI (e.g. a dct:identifier) that contain a generic placeholder {{context.id}}

However entering the {} characters is not supported.

```
Caused by: java.net.URISyntaxException: Illegal character in path at index 34: https://marineinfo.org/id/dataset/{{context.id}}
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3116)
	at java.base/java.net.URI.<init>(URI.java:600)
```

**Comment by vvalerio** [comment]
The {} characters are not supported for URI objects, the internal engine checks if the string you entered is a valid URL and https://marineinfo.org/id/dataset/{{context.id}} is not a valid URL.
However you could put a dct:identifier as string, this means that the check is not executed and everything works fine.
This is a result on the Dataset object:
<img width="1407" alt="Schermata 2020-12-04 alle 13 09 21" src="https://user-images.githubusercontent.com/26569362/101162190-4b07d000-3632-11eb-969f-afa78d73d222.png">
<img width="637" alt="Schermata 2020-12-04 alle 13 12 42" src="https://user-images.githubusercontent.com/26569362/101162289-6bd02580-3632-11eb-9a9f-04fa848eb9bf.png">

**Comment by epos-eu** [comment]
Not an issue.
